config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :acts
  resources :tasks
  resources :staff_users
  resources :staff_groups
  get "doc/index"
  devise_for :users
  get "welcome/index"
  get "dashboard/index"
  get "doc", to: "doc#index"
  get "doc/*path", to: "doc#show"
  root "welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  mount Lookbook::Engine, at: "/lookbook" if Rails.env.development?

  telegram_webhook TelegramWebhooksController
end

app/models/staff_group.rb
# frozen_string_literal: true

# Groups of staff members
class StaffGroup < ApplicationRecord
  attribute :active, :boolean, default: true

  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name, length: { maximum: 255 }

  has_many :staff_group_membership, dependent: :delete_all
  has_many :staff_users, through: :staff_group_membership
  has_many :task_assignments, as: :assignee, dependent: :destroy
  has_many :tasks, through: :task_assignments
end

app/controllers/staff_groups_controller.rb
# frozen_string_literal: true

# A controller for StaffGroup
class StaffGroupsController < ProtectedController
  def index
    @staff_groups = StaffGroup.all
  end

  def show
    @staff_group = StaffGroup.find_by(id: params[:id])
  end

  def new
    @staff_group = StaffGroup.new
  end

  def edit
    @staff_group = StaffGroup.find(params[:id])
    render :index unless @staff_group
  end

  def create
    @staff_group = StaffGroup.new(staff_group_params)
    if @staff_group.save
      redirect_to staff_group_path(@staff_group), notice: "Created #{@staff_group.name}."
    else
      flash[:alert] = I18n.t("resource_missing")
    end
  end

  def update
    @staff_group = StaffGroup.find_by(id: params[:id])
    if @staff_group.update(staff_group_params)
      redirect_to @staff_group, notice: "Updated #{@staff_group.name}"
    else
      render :edit
    end
  end

  def destroy
    @staff_group = StaffGroup.find_by(id: params[:id])
    if @staff_group.destroy
      redirect_to staff_groups_path, notice: "Deleted #{@staff_group.name}."
    else
      flash[:alert] = I18n.t("resource_missing")
    end
  end

  private

  def staff_group_params
    params.expect(staff_group: [:name])
  end
end

app/views/staff_groups/edit.html.erb
<h2>Edit a role</h2>
<%= bootstrap_form_with(model: @staff_group) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Save" %>
  <%= render Button::LinkComponent.new("Cancel", staff_groups_path) %>
<% end %>

app/views/staff_groups/index.html.erb
<%= render Table::WithActionsComponent.new(title: "Roles", columns: ["name"], items: @staff_groups) do %>
  <%= render Button::LinkComponent.new("Create Role", new_staff_group_path) %>
<% end %>

app/views/staff_groups/new.html.erb
<h2>Create a role</h2>
<%= bootstrap_form_with(model: @staff_group) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Save" %>
  <%= render Button::LinkComponent.new("Cancel", staff_groups_path) %>
<% end %>

app/views/staff_groups/show.html.erb
<%= render StaffGroup::ShowComponent.new(@staff_group) %>