config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :acts
  resources :tasks
  resources :staff_users
  resources :staff_groups
  get "doc/index"
  devise_for :users
  get "welcome/index"
  get "dashboard/index"
  get "doc", to: "doc#index"
  get "doc/*path", to: "doc#show"
  root "welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  mount Lookbook::Engine, at: "/lookbook" if Rails.env.development?

  telegram_webhook TelegramWebhooksController
end

app/models/staff_user.rb
# frozen_string_literal: true

# A class to represent staffs, who is notified, messaged, and managed by the
# application.
class StaffUser < ApplicationRecord
  validates :name, presence: true
  validates :display_name, presence: true
  validates :account, presence: true
  validates :active, inclusion: { in: [true, false] }
  validates :active, exclusion: { in: [nil] }
  validates :account, format: { with: /\A[a-zA-Z0-9_]+\z/ }
  validates :account, length: { in: 5..32 }

  has_many :staff_group_membership, dependent: :delete_all
  has_many :staff_groups, through: :staff_group_membership
  has_many :task_assignments, as: :assignee, dependent: :destroy
  has_many :tasks, through: :task_assignments
end

app/controllers/staff_users_controller.rb
# frozen_string_literal: true

# A controller to handle StaffUser
class StaffUsersController < ProtectedController
  before_action :set_staff_user, only: [:show, :edit, :update, :destroy]

  # GET /staff_users or /staff_users.json
  def index
    @staff_users = StaffUser.all
  end

  # GET /staff_users/1 or /staff_users/1.json
  def show; end

  # GET /staff_users/new
  def new
    @staff_user = StaffUser.new
  end

  # GET /staff_users/1/edit
  def edit; end

  # POST /staff_users or /staff_users.json
  # rubocop:disable Metrics/MethodLength
  def create
    @staff_user = StaffUser.new(staff_user_params)

    respond_to do |format|
      if @staff_user.save
        format.html do
          redirect_to @staff_user, notice: I18n.t("staff_user.create.staff_user_successfully_created.content")
        end
        format.json { render :show, status: :created, location: @staff_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staff_users/1 or /staff_users/1.json
  def update
    respond_to do |format|
      if @staff_user.update(staff_user_params)
        format.html do
          redirect_to @staff_user, notice: I18n.t("staff_user.update.staff_user_successfully_updated.content")
        end
        format.json { render :show, status: :ok, location: @staff_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff_user.errors, status: :unprocessable_entity }
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  # DELETE /staff_users/1 or /staff_users/1.json
  def destroy
    @staff_user.delete

    respond_to do |format|
      format.html do
        redirect_to staff_users_path, status: :see_other,
                                      notice: I18n.t("staff_user.destroy.staff_user_successfully_destroyed.content")
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_staff_user
    @staff_user = StaffUser.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def staff_user_params
    params.expect(
      staff_user: [
        :name,
        :account,
        :display_name,
        :active,
        { staff_group_ids: [] }
      ]
    )
  end
end

app/helpers/staff_users_helper.rb
# frozen_string_literal: true

# Helper for StaffUsers
module StaffUsersHelper
end

app/views/staff_users/edit.html.erb
<% content_for :title, "Editing staff user" %>

<h1>Editing staff user</h1>

<%= render StaffUser::FormComponent.new(@staff_user) %>

<br>

<div>
  <%= link_to "Show this staff user", @staff_user %> |
  <%= link_to "Back to staff users", staff_users_path %>
</div>

app/views/staff_users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Staff users" %>

<h1>Staff users</h1>

<div id="staff_users">
  <%= render StaffUser::ListComponent.new(@staff_users) %>
</div>

<%= link_to "New staff user", new_staff_user_path %>

app/views/staff_users/new.html.erb
<% content_for :title, "New staff user" %>

<h1>New staff user</h1>

<%= render StaffUser::FormComponent.new(@staff_user) %>

<br>

<div>
  <%= link_to "Back to staff users", staff_users_path %>
</div>

app/views/staff_users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render StaffUser::ShowComponent.new(@staff_user) %>

<div>
  <%= link_to "Edit this staff user", edit_staff_user_path(@staff_user) %> |
  <%= link_to "Back to staff users", staff_users_path %>

  <%= button_to "Destroy this staff user", @staff_user, method: :delete %>
</div>