config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :acts
  resources :tasks
  resources :staff_users
  resources :staff_groups
  get "doc/index"
  devise_for :users
  get "welcome/index"
  get "dashboard/index"
  get "doc", to: "doc#index"
  get "doc/*path", to: "doc#show"
  root "welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  mount Lookbook::Engine, at: "/lookbook" if Rails.env.development?

  telegram_webhook TelegramWebhooksController
end

app/models/act.rb
# frozen_string_literal: true

# A class that takes an action in Task
class Act < ApplicationRecord
  include Recurrable
  include RecurrenceBuildable

  validates :active, inclusion: { in: [true, false] }
  validates :name, presence: true
  validates :starts_at, presence: true

  belongs_to :task
end

app/models/act/recurring.rb
# frozen_string_literal: true

# A model of in-memory, recurring Act from Act.
class Act::Recurring
  include ActiveModel::Model

  delegate :name, :active, :description, :task_id, :recurring_rule, :schedule, to: :@act
  attr_reader :starts_at

  def initialize(act, starts_at)
    @act = act
    @starts_at = starts_at
  end

  def persisted?
    false
  end
end

app/controllers/acts_controller.rb
# frozen_string_literal: true

# A controller to manage Act
class ActsController < ApplicationController
  before_action :set_act, only: [:show, :edit, :update, :destroy]

  # GET /acts or /acts.json
  def index
    @acts = Act.all
  end

  # GET /acts/1 or /acts/1.json
  def show; end

  # GET /acts/1/edit
  def edit
    @task = @act.task
  end

  # POST /acts or /acts.json
  def create
    @act = Act.new(act_params)

    respond_to do |format|
      if @act.save
        format.html { redirect_back_or_to @act, notice: I18n.t("act.act_successfully_created") }
        format.json { render :show, status: :created, location: @act }
      else
        format.html { redirect_back_or_to @act, status: :unprocessable_entity }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acts/1 or /acts/1.json
  def update
    respond_to do |format|
      if @act.update(act_params)
        format.html { redirect_back_or_to @act, notice: I18n.t("act.act_successfully_updated") }
        format.json { render :show, status: :ok, location: @act }
      else
        format.html { redirect_back_or_to @act, status: :unprocessable_entity }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acts/1 or /acts/1.json
  def destroy
    @act.destroy!

    respond_to do |format|
      format.html { redirect_to acts_path, status: :see_other, notice: I18n.t("act.act_successfully_deleted") }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_act
    @act = Act.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def act_params
    filtered_params = params.expect(act: allowed_params)
    filtered_params[:task] = Task.find_by(id: filtered_params[:task])
    if filtered_params.key? :recurring_until
      filtered_params[:recurring_until] = Time.zone.parse(filtered_params[:recurring_until])
    end
    filtered_params
  end

  def allowed_params
    [
      :name,
      :active,
      :description,
      :task, :starts_at,
      :recurring_type,
      :recurring_until
    ]
  end
end

app/helpers/acts_helper.rb
# frozen_string_literal: true

# A helper for Act
module ActsHelper
end

app/views/acts/_act.html.erb
<div id="<%= dom_id act %>">
  <p>
    <strong>Name:</strong>
    <%= act.name %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= act.active %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= act.description %>
  </p>

</div>

app/views/acts/_form.html.erb
<%= form_with(model: act) do |form| %>
  <% if act.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(act.errors.count, "error") %> prohibited this act from being saved:</h2>

      <ul>
        <% act.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.checkbox :active %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/acts/edit.html.erb
<% content_for :title, "Editing act" %>

<h1>Editing act</h1>
<p>This act is used in Task <%= link_to @task.name, @task %></p>
<%= render Act::FormComponent.new(@act, @task) %>

<br>

<div>
  <%= link_to "Show this act", @act %> |
  <%= link_to "Back to acts", acts_path %>
</div>

app/views/acts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Acts" %>

<h1>Acts</h1>

<div id="acts">
  <% @acts.each do |act| %>
    <%= render act %>
    <p>
      <%= link_to "Show this act", act %>
    </p>
  <% end %>
</div>

<%= link_to "New act", new_act_path %>

app/views/acts/new.html.erb
<% content_for :title, "New act" %>

<h1>New act</h1>

<%= render "form", act: @act %>

<br>

<div>
  <%= link_to "Back to acts", acts_path %>
</div>

app/views/acts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render Act::DetailCardComponent.new @act %>

<div>
  <%= link_to "Edit this act", edit_act_path(@act) %> |
  <%= link_to "Back to acts", acts_path %>

  <%= button_to "Destroy this act", @act, method: :delete %>
</div>